export const ACTIVE_TOAST_BOX = 'toast/CLICKED';
export const PUSH_TOASTER_TO_QUEUE = 'PUSH_TOASTER_TO_QUEUE';
export const SHIFT_TOASTER_FROM_QUEUE = 'SHIFT_TOASTER_FROM_QUEUE';
export const SHOW_TOASTER = 'SHOW_TOASTER'
export const HIDE_TOASTER = 'HIDE_TOASTER'
